export { default as withInstall } from './withinstall';
export { default as isObject } from './dataType';
export { default as localStorage } from './localStorage';
export { default as sessionStorage } from './sessionStorage';
export { default as waterMark } from './waterMark';
export * from './download';
export *  from './color-thief';
export { default as dayjs }  from 'dayjs';
export * as date from './date';
export * from './type';
export *  from './canvas-sign';